cart/urls.py
from django.urls import path, include
from . import views
app_name='cart'
urlpatterns = [
    path('', views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>', views.add_cart,name='add_cart'),
    path('remove_by_one/<int:product_id>', views.cart_remove,name='remove_by_one'),
    path('clear_cart/<int:product_id>', views.clear_cart,name='clear_cart'),
]

ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns = [
    path('', views.search_results,name="search_results"),
]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
    path('', views.all_prod_cat,name='all_prod_cat'),
    path('shop/<slug:c_slug>/', views.all_prod_cat,name='products_by_category'),
    path('shop/<slug:c_slug>/<slug:p_slug>/', views.prod_details,name='prod_details'),
]

cart/models.py
from django.db import models
from django.urls import reverse

from shop.models import Product

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)


    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

search_app/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)



    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop:prod_details',args=[self.category.slug,self.slug])


    def __str__(self):
        return '{}'.format(self.name)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity <= cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            cart=cart,
            quantity=1,
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_items = CartItem.objects.get(cart=cart, product=product)
    if cart_items.quantity > 1:
        cart_items.quantity -=1
        cart_items.save()
    else:
        cart_items.delete()

    return redirect('cart:cart_detail')

def clear_cart(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_items = CartItem.objects.get(cart=cart, product=product)
    cart_items.delete()
    return redirect('cart:cart_detail')

search_app/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from shop.models import Product


def search_results(request):
    query = None
    products = None
    if 'search' in request.GET:
        query = request.GET.get('search')
        products = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    if not query:
        return redirect('/')
    else:
        return render(request, 'search.html', {'query': query, 'products': products})

shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage



def all_prod_cat(request,c_slug=None):
    c_page=None
    product_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        product_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        product_list = Product.objects.all().filter(available=True)
    paginator=Paginator(product_list,6)
    try:
        page=int(request.GET.get('page',1))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'products':products})

def prod_details(request,c_slug,p_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=p_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block description %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container" style="max-width:1550px">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block description %}
     This is cart page.Proceed to review your items and place the order
{% endblock %}
{% block title %}
     Cart - AK Shop
{% endblock %}
{% block content %}
<style>
    .my-footer{
      display: none;
    }
    .search-footer{
      background-color: #f8f9fa;
      height: 60px;
    }
    .search-footer p{
      padding-top:20px;
      font-size:15px
   }
</style>
{% if not cart_items %}
<div>
     <div>
          <br>
          <h1 class="text-center my-title">Your cart is empty</h1>
          <br>
          <p class="text-center">Please click <a href="{% url 'shop:all_prod_cat' %}"> here</a> to continue shoppig</p>
     </div>

</div>
{% else %}
<div>
     <div>
          <br>
          <h1 class="text-center">Your Cart</h1>
          <br>
     </div>
</div>
<div class="row mx-auto">
     <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my-custom-table">
          <thead class="my-custom-table-thead">
          <tr>
            <th colspan="4">Your Items</th>
          </tr>
          </thead>
          <tbody>
          {% for cart_item in cart_items %}
          <tr>
            <td>
                <a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.image.url}}" alt="{{cart_item.product.name}}" class="float-left rounded custom-image"></a>
            </td>
            <td>
                 Item: {{cart_item.product.name}}<br>
                 IDN: #{{cart_item.product.id}}<br>
                 Price: &#8377; {{cart_item.product.price}}<br>
                 Qty: x {{cart_item.quantity}}
            </td>
            <td>
              &#8377; {{cart_item.sub_total}}
            </td>
              {% if cart_item.quantity <= cart_item.product.stock %}
              <td>
                  <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom-a"><img src = "{% static 'img/plus.png' %}" alt="Plus"/></a>
                  &nbsp;<a href="{% url 'cart:remove_by_one' cart_item.product.id %}" class="custom-a"><img src = "{% static 'img/minus.png' %}" alt="Minus"/></a>
                  &nbsp;<a href="{% url 'cart:clear_cart' cart_item.product.id %}" class="custom-icon"><img src = "{% static 'img/trash.png' %}" alt="Trash"/></a>

              </td>
              {% else %}
               <td>
                  &nbsp;<a href="{% url 'cart:remove_by_one' cart_item.product.id %}" class="custom-a"><img src = "{% static 'img/minus.png' %}" alt="Minus"/></a>
                  &nbsp;<a href="{% url 'cart:clear_cart' cart_item.product.id %}" class="custom-icon"><img src = "{% static 'img/trash.png' %}" alt="Trash"/></a>
               </td>
              {% endif %}
          </tr>
          {% endfor %}
          </tbody>
        </table>
     </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my-custom-table">
          <thead class="my-custom-table-thead">
              <tr>
                <th>Checkout</th>
              </tr>
          </thead>
          <tbody>
            <tr>
                <td> Please review your cart items before proceeding with the order payment.</td>
            </tr>
          </tbody>
            <tfoot>
            <tr>
                <td>
                    <h5>Items total quantity : {{counter}}</h5>
                    <h5>Grand total : &#8377; {{total}}</h5>
                </td>
            </tr>
            </tfoot>
        </table>
        <div class="mx-auto">
           <a href="{% url 'shop:all_prod_cat' %}" class="btn btn-secondary btn-block my-custom-button">Continue Shopping</a>
        </div>
    </div>
</div>
{% endif %}
<div class="footer fixed-bottom search-footer">
    <p class="text-center">&copy;AK tech pvt ltd.All rights reserved.</p>
</div>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block description %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to AK Shop where you can buy different anything you want....
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name}} - AK Shop
    {% else %}
        See our New Collections - AK Shop
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my-row">
                <div class="mx-auto">
                    <p><a href="{% url 'shop:all_prod_cat' %}">Our Product Collections</a></p>
                </div>
            </div>
        </div>
    {% endif %}
    {% if category %}
    <div class="mx-auto">
        <img class="my-image" style="height:527px;"  src="{{category.image.url}}" alt="{{category.name}}">
    </div><br>
    <div>
        <h1 class="text-center my-title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
        {% else %}
    <div>
        <img class="my-image my-image-padding" src="{% static 'img/banner.png' %}" alt="our products">
    </div><br>
    <div>
        <h1 class="text-center my-title">Our Product Collections</h1>
        <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
    </div>
       {% endif %}

<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="my-image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>&#8377; {{product.price}}</p>
                </div>
                </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-sm {% if products.number == pg %} active btn-primary {% else %} btn-secondary {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div><br>
</div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my-footer">
    <p class="text-center">&copy;AK tech pvt ltd.All rights reserved.</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:all_prod_cat' %}"><img src="{% static 'img/logo.png' %}" class="mt-3" alt="logo" width="100px" height="100px"></a>
    </center>
</header>

templates/navbar.html
{% load static %}
<nav class="mt-3 navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:all_prod_cat' %}"><b>Home</b></a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <b>Shop</b>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:all_prod_cat' %}">All Products</a></li>
              {% for cat in links %}
              <li><a class="dropdown-item" href="{{ cat.get_url }}">{{cat.name}}</a></li>
              {% endfor %}


          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><img src = "{% static 'img/cart.png' %}" alt="Cart"/>{% if item_count > 0%}({{item_count}}){% else %}(0){% endif %}</a>
        </li>

      </ul>
      <form class="d-flex" action="{% url 'search_app:search_results' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" autocomplete="off" name='search' value="{{query}}" placeholder="Search products here" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><img src = "{% static 'img/search.svg' %}" alt="Search"/></button>
      </form>
    </div>
  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block description %}
     {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
     {{ product.name}} - AK Shop
{% endblock %}
{% block content %}
<div class="row my-product-row-class">
    <div class="mx-auto">
        <p><a href="{% url 'shop:all_prod_cat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>
            | {{product.name}}</p>
    </div>
</div><br>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div>
                <img alt="{{product.name}}" src="{{product.image.url}}">
            </div>
        </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my-product-title">{{product.name}}</h1>
                <p>&#8377; {{product.price}}</p>
                <p class="my-title">Product Description</p>
                <p class="text-justify my-product-text">{{product.description}}</p>
                {% if product.stock <= 0 %}
                <p class="text-justify my-product-text"><b>Out of Stock</b></p>
                {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block description %}
     We have variety of products
{% endblock %}
{% block title %}
     Search - AK Shop
{% endblock %}
{% block content %}
<style>
    .my-footer{
      display: none;
    }
    .search-footer{
      background-color: #f8f9fa;
      height: 60px;
    }
    .search-footer p{
      padding-top:20px;
      font-size:15px
   }
</style>
<div>
    <h5 class="text-center my-search-text">You have searched for: <b>"{{query}}"</b></h5>
</div>
<div class="container">
    <div class="row mx-auto">
        {% if products %}
        {% for product in products %}
        <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="my-image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>&#8377; {{product.price}}</p>
                </div>
                </div>
        </div>

        {% endfor %}
        {% else %}
        <div class="row mx-auto">
            <p class="text-center my-search-text">No Results found</p>
        </div>
        {% endif %}
    </div>
</div>
<div class="footer fixed-bottom search-footer">
    <p class="text-center">&copy;AK tech pvt ltd.All rights reserved.</p>
</div>
{% endblock %}